# setup

In [1]:
import os

if os.getcwd().split('/')[-1] == 'notebooks':
    os.chdir('..')

In [2]:
import torch

from tqdm import tqdm

In [3]:
from dataloaders.code import CODE, CODEsplit

# draft

In [9]:
# import h5py
# import pandas as pd
# import numpy as np

In [10]:
# hdf5_path = '/home/josegfer/code/codetest/data/ecg_tracings.hdf5'
# metadata_path = '/home/josegfer/code/codetest/data/annotations/gold_standard.csv'

In [11]:
# hdf5_file = h5py.File(hdf5_path, "r")
# hdf5_file, hdf5_file['tracings']

(<HDF5 file "ecg_tracings.hdf5" (mode r)>,
 <HDF5 dataset "tracings": shape (827, 4096, 12), type "<f8">)

In [17]:
# metadata = pd.read_csv(metadata_path)
# metadata

1dAVb  RBBB  LBBB  SB  AF  ST
0        0     0     0   0   0   0
1        0     0     1   0   0   0
2        0     0     0   0   0   0
3        0     0     0   0   0   0
4        0     0     0   0   0   0
..     ...   ...   ...  ..  ..  ..
822      0     0     0   0   0   0
823      0     0     0   0   0   0
824      0     0     0   0   0   0
825      0     0     0   0   0   0
826      1     0     0   0   0   0

[827 rows x 6 columns]

In [18]:
# metadata['exam_id'] = metadata.index
# metadata['h5_idx'] = metadata.index
# metadata['csv_idx'] = metadata.index
# metadata

1dAVb  RBBB  LBBB  SB  AF  ST  exam_id  h5_idx  csv_idx
0        0     0     0   0   0   0        0       0        0
1        0     0     1   0   0   0        1       1        1
2        0     0     0   0   0   0        2       2        2
3        0     0     0   0   0   0        3       3        3
4        0     0     0   0   0   0        4       4        4
..     ...   ...   ...  ..  ..  ..      ...     ...      ...
822      0     0     0   0   0   0      822     822      822
823      0     0     0   0   0   0      823     823      823
824      0     0     0   0   0   0      824     824      824
825      0     0     0   0   0   0      825     825      825
826      1     0     0   0   0   0      826     826      826

[827 rows x 9 columns]

In [4]:
data = CODE()

checking exam_id consistency in idx dict
checking exam_id consistency in idx dict
checking exam_id consistency in idx dict


In [6]:
pretrn_ds = CODEsplit(data, data.pretrn_idx_dict)
trn_ds = CODEsplit(data, data.trn_idx_dict)
val_ds = CODEsplit(data, data.val_idx_dict)
tst_ds = CODEsplit(data, data.tst_idx_dict)

In [7]:
pretrn_loader = torch.utils.data.DataLoader(pretrn_ds, batch_size = 128,
                                          shuffle = True, num_workers = 6)
trn_loader = torch.utils.data.DataLoader(trn_ds, batch_size = 128,
                                          shuffle = True, num_workers = 6)
val_loader = torch.utils.data.DataLoader(val_ds, batch_size = 128,
                                          shuffle = False, num_workers = 6)
tst_loader = torch.utils.data.DataLoader(tst_ds, batch_size = 128,
                                          shuffle = False, num_workers = 6)

In [9]:
for batch in tqdm(pretrn_loader):
    break
batch['X'].shape, batch['X'], batch['y'].shape, batch['y'], batch['H'].shape, batch['H']

  0%|          | 0/2038 [00:23<?, ?it/s]


(torch.Size([128, 4096, 12]),
 tensor([[[ 0.4116, -1.3796, -1.7912,  ...,  0.0534, -1.9360, -0.9756],
          [ 0.4073, -1.3832, -1.7906,  ...,  0.0457, -1.9407, -0.9760],
          [ 0.3957, -1.3929, -1.7886,  ...,  0.0495, -1.9397, -0.9700],
          ...,
          [ 1.1647, -1.0658, -2.2305,  ..., -2.5445, -1.7816, -1.2193],
          [ 1.1661, -1.0693, -2.2354,  ..., -2.5462, -1.7852, -1.2214],
          [ 1.1641, -1.0752, -2.2393,  ..., -2.5525, -1.7910, -1.2272]],
 
         [[-0.7012, -0.0076,  0.6936,  ..., -2.2180, -0.1372, -0.5564],
          [-0.7012, -0.0143,  0.6869,  ..., -2.2219, -0.1415, -0.5619],
          [-0.7000, -0.0152,  0.6848,  ..., -2.2271, -0.1530, -0.5672],
          ...,
          [-0.0364,  0.0268,  0.0632,  ..., -2.0435, -1.0707, -1.5248],
          [ 0.0640,  0.1389,  0.0748,  ..., -1.8845, -0.8708, -1.3586],
          [ 0.2010,  0.2757,  0.0747,  ..., -1.6891, -0.5917, -1.1120]],
 
         [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]

In [8]:
for batch in tqdm(trn_loader):
    break
batch['X'].shape, batch['X'], batch['y'].shape, batch['y'], batch['H'].shape, batch['H']

  0%|          | 0/178 [00:24<?, ?it/s]


(torch.Size([128, 4096, 12]),
 tensor([[[ 1.5549,  3.2317,  1.6768,  ..., -1.4634, -2.3857, -2.9269],
          [ 1.5491,  3.2231,  1.6740,  ..., -1.4573, -2.3790, -2.9200],
          [ 1.5370,  3.2182,  1.6812,  ..., -1.4517, -2.3702, -2.9085],
          ...,
          [ 2.4564,  3.2866,  0.8302,  ..., -1.8428, -2.7823, -3.1301],
          [ 2.4677,  3.2971,  0.8293,  ..., -1.8426, -2.7772, -3.1292],
          [ 2.4769,  3.3085,  0.8317,  ..., -1.8440, -2.7815, -3.1312]],
 
         [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]

In [10]:
for batch in tqdm(val_loader):
    break
batch['X'].shape, batch['X'], batch['y'].shape, batch['y'], batch['H'].shape, batch['H']

  0%|          | 0/189 [00:21<?, ?it/s]


(torch.Size([128, 4096, 12]),
 tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.4726, -0.0534, -0.5259,  ..., -1.1128,  0.3887,  0.9756]

In [11]:
for batch in tqdm(tst_loader):
    break
batch['X'].shape, batch['X'], batch['y'].shape, batch['y'], batch['H'].shape, batch['H']

  0%|          | 0/7 [00:03<?, ?it/s]


(torch.Size([128, 4096, 12]),
 tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          ...,
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00]],
 
         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.